### ISSUE TITLE
Set up AWS account

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven-team#14]
Account name: aws-dsh-dev01
ID: 8911-2282-9292
email: aws-dsh-dev01@turing.ac.uk

Tomas isn't sure how to set this up or if it works similar to an AWS subscription, so I plan to look into this myself

**Comment by manics** [comment]
If it's got its own account number I'd assume it's a full AWS account (and most likely part of an AWS Organisation).
