### ISSUE TITLE
Co-create a TRE standard

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/data-safe-haven-team#23]
# Goal Title
_What will this work achieve?_
Develop the SATRE specification that UK TREs can evaluate themselves against

## Description
- Write the specification
- Evaluate existing TREs against the specification
- Plan necessary work to meet missing requirements

## Definition of Done
SATRE specification published

### Details
- RACI
  - Accountable team or person: @jemrobinson @martintoreilly @harisood
  - Responsible team or person: SATRE team
  - Informed and consulted people: UK TRE community
- Estimated effort FTE: 1.8
  - RPM: 0.05 + #38 

#### August
- REG: 2
- RAM: 0.75
- RPM: 0.1 (excluding contracts)

### Task and issue breakdown
Breakdown in specific tasks of maximum a month duration, tasks and issues may be added as necessary
Issues may span across repositories when necessary.

•	WP1 - Evaluation and Reference Specification.
•	WP2: Patient and Public Involvement and Engagement (PPIE).
•	WP3: Formalisation of the pluggable reference architecture
•	WP4: Implementation and assessment of a reference TRE architecture
•	WP 5: Community building & engagement

The specification (output) lives [here](https://github.com/sa-tre/satre-team) and the project activites is recorded [here](https://github.com/sa-tre/satre-specification)

### 1 November 4 December

Had wrap-up and post project meeting, it was identified how ongoing work it is necessary to communicate and ensure engagement and usage as well as to prepare for the next DARE phase.

We have decided to keep fortnightly meetings to keep some momentum.

Is that enough? do we want to dedicate any more resources to ensure the necessary actions happen?

### 10 October to 30 October 2023

- Final month of this funded phase, we have focused on reporting and laying out the next steps. There is commitment to take this work and the specification forward
- Outputs:
  - SATRE specification V1
  - Internal DARE report, link will be added and published openly
  - User report: characterises users, with a wider notion than we started of what users are. Lays the fundation for futher usability work, going beyong technicla features and into training and documentation
  - UK TRE Community - SATRE WG
- final project showcase, presenting the work done for SATRE (Chris presented as PI with slides prepared by each wp), and the final project meeting and collaboration café
- Held the self-evaluation workshop
- During the last proejct meeting it was decided to have yet another one focused on next steps and possibilites for collaboration

### 19 September to 9 October 2023
- Specification v1, announcements to go out wc 9Oct. Big focus of the team on wp1
- Stakeholder engagement: self-evaluation invitation and event on 25 October
- Collab cafes:
  -  on the UX of the specification: resulted in changes. [notes](https://hackmd.io/z4paFsGVRHSbW7abuaV0ig?edit) including suggestions on FAQs
  - Session with members of the public, invite only
  - Unstructured collab cafe: 3 attendees, useful conversation on possible ways to make PPIE a part of future specs/standards. [Notes here](https://hackmd.io/sG5n2IBNRMCxzBJacqjgVg)
- Spec changes:
  - Added [FAQs page](https://github.com/sa-tre/satre-specification/pull/237) 
  - Added some suggestions from [HDR UK](https://github.com/sa-tre/satre-specification/pull/242/files)
  - Updating evaluation of the DSH to include answers to new statements [PR#271](https://github.com/sa-tre/satre-specification/pull/271)
  - Next month priority: reporting
    - 11 October: share materials with Chris or showcase
    - 20 October: finalise each WP report
    - 31 October: final report due, to be submitted by Dundee

### 14 August to 18 September 2023
- [Self evaluation](https://satre-specification.readthedocs.io/en/latest/evaluations/alan_turing_institute.html): via several long sessions DSH was evaluated against SATRE specification. [Merged PR](https://github.com/sa-tre/satre-specification/pull/196)
  - Producing evaluations for DSH and TREEHOOSE is a key objective of SATRE
  - Takeaways: @JimMadge @jemrobinson @harisood do you have takeways/lessons to share form the slef evaluation?
  - Method of evaluation: from a suggestion in a collaboration cafe it was suggested to create a tiered evaluation system which DSH agrees would be valuable and appropiatte, there is not however resources to make it happen as part of DARE funded SATRE. Will consider as future work
  - Scoring system was revised to be clearer
- RSEcon presentation: prepared materials for talk presenting the project and progress. On top of the specific talk the TRE Community day also had short talks and led to discussions on the project and the need for specifications
  - Throughtout the days at RSEcon attendees showed interest on SATRE and expressed the need for it
- Continued adding to the specification: added statements on [output checking](https://github.com/sa-tre/satre-specification/pull/199), draft PR to edit and include [TRE roles](https://github.com/sa-tre/satre-specification/pull/211)
- Collaboration cafes
  - Wrote blogs about previous collaboration cafes on Usability and Implementaiton, text on Teams [here](https://dmail.sharepoint.com/:w:/r/sites/SATRE/Shared%20Documents/General/Blog%20posts/Usability%20ColabCafe%20Blog%2020%20July.docx?d=w34606f668d094e98b87243a898dd0e51&csf=1&web=1&e=4WK0Kl) & Principles, text on Teams [here](https://dmail.sharepoint.com/:w:/r/sites/SATRE/Shared%20Documents/General/Blog%20posts/Principles_Implications.docx?d=w728fae6495584b5287f95cbee92fd6d4&csf=1&web=1&e=I4As39)
  - Held collaboration cafes on evaluation methods
### 10 July to 14 August 2023
- Closing off SATRE survey, analysis of free text responses. Output:
- Collaboration cafes on [Usability and Implementation](https://hackmd.io/JUQHNg4CROWFt7BKi_9a7Q) and [Principles and implications](https://hackmd.io/fDfeb2D9RTqYCa41LQlJtw)
  - Outputs:  working on blog posts and converting discussion points into issues in the specification repo
- User Testing: lead by Turing, facilitated by Ulster. Usability test of DSH and TREEHOOSE with a common analysis challenge. It was possible thanks to Turing approved ethics
  - Output: additional data necessary for the project report on Users
- DSA draft shared & FY22-23 Q1 Invoiced (#22)
- Specification changes through PRs [1](https://github.com/sa-tre/satre-specification/pull/132) [2](https://github.com/sa-tre/satre-specification/pull/153) which relate to loggin user actions, added sections for security levels and tiering. Changes to Computing Pillar via https://github.com/sa-tre/satre-specification/pull/186
- Self evaluation

**Comment by Davsarper** [comment]
I have translated weekly updates into reporting in the issue body, please use comments to discuss and complete
- I have not reported on [3](https://github.com/sa-tre/satre-specification/pull/118) as it is closed but not merged?
- Self evaluation detail needed
- @harisood and @jemrobinson please review and add outputs/value where needed. What did the activites above deliver?

**Comment by harisood** [comment]
I am now seeing the benefit of recording everything on here for reporting purposes... I think it looks good, maybe highlighting how long the self-evaluation is taking

**Comment by Davsarper** [comment]
October: porject closure, reporting, meet in Edinburgh.. both priority and urgent
